"use client";

import { Inter } from "next/font/google";
import "./globals.css";
import { CookiesProvider } from "react-cookie";

const inter = Inter({ subsets: ["latin"] });

const metadata = {
  title: "Task Management App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <CookiesProvider defaultSetOptions={{ path: "/" }}>
          {children}
        </CookiesProvider>
      </body>
    </html>
  );
}
